import { v } from "convex/values";

export const browseGalaxiesArgs = {
  offset: v.number(),
  numItems: v.number(),
  cursor: v.optional(v.string()),
  sortBy: v.optional(v.union(
    v.literal("id"),
    v.literal("ra"),
    v.literal("dec"),
    v.literal("reff"),
    v.literal("q"),
    v.literal("pa"),
    v.literal("mag"),
    v.literal("mean_mue"),
    v.literal("nucleus"),
    v.literal("numericId"),
    v.literal("totalClassifications"),
    v.literal("numVisibleNucleus"),
    v.literal("numAwesomeFlag"),
    v.literal("numFailedFitting"),
    v.literal("totalAssigned")
  )),
  sortOrder: v.optional(v.union(v.literal("asc"), v.literal("desc"))),
  filter: v.optional(v.union(
    v.literal("all"),
    v.literal("my_sequence"),
    v.literal("classified"),
    v.literal("unclassified"),
    v.literal("skipped")
  )),
  searchTerm: v.optional(v.string()),
  searchId: v.optional(v.string()),
  searchRaMin: v.optional(v.string()),
  searchRaMax: v.optional(v.string()),
  searchDecMin: v.optional(v.string()),
  searchDecMax: v.optional(v.string()),
  searchReffMin: v.optional(v.string()),
  searchReffMax: v.optional(v.string()),
  searchQMin: v.optional(v.string()),
  searchQMax: v.optional(v.string()),
  searchPaMin: v.optional(v.string()),
  searchPaMax: v.optional(v.string()),
  searchMagMin: v.optional(v.string()),
  searchMagMax: v.optional(v.string()),
  searchMeanMueMin: v.optional(v.string()),
  searchMeanMueMax: v.optional(v.string()),
  searchNucleus: v.optional(v.boolean()),
  searchTotalClassificationsMin: v.optional(v.string()),
  searchTotalClassificationsMax: v.optional(v.string()),
  searchNumVisibleNucleusMin: v.optional(v.string()),
  searchNumVisibleNucleusMax: v.optional(v.string()),
  searchNumAwesomeFlagMin: v.optional(v.string()),
  searchNumAwesomeFlagMax: v.optional(v.string()),
  searchNumFailedFittingMin: v.optional(v.string()),
  searchNumFailedFittingMax: v.optional(v.string()),
  searchTotalAssignedMin: v.optional(v.string()),
  searchTotalAssignedMax: v.optional(v.string()),
  searchAwesome: v.optional(v.boolean()),
  searchValidRedshift: v.optional(v.boolean()),
  searchVisibleNucleus: v.optional(v.boolean()),
};
