import { v } from "convex/values";
import {
  galaxyBrowserFilterValidator,
  galaxyBrowserSortFieldValidator,
  galaxyBrowserSortOrderValidator,
} from "./viewState";

export const browseGalaxiesArgs = {
  offset: v.number(),
  numItems: v.number(),
  cursor: v.optional(v.string()),
  sortBy: v.optional(galaxyBrowserSortFieldValidator),
  sortOrder: v.optional(galaxyBrowserSortOrderValidator),
  filter: v.optional(galaxyBrowserFilterValidator),
  searchTerm: v.optional(v.string()),
  searchId: v.optional(v.string()),
  searchRaMin: v.optional(v.string()),
  searchRaMax: v.optional(v.string()),
  searchDecMin: v.optional(v.string()),
  searchDecMax: v.optional(v.string()),
  searchReffMin: v.optional(v.string()),
  searchReffMax: v.optional(v.string()),
  searchQMin: v.optional(v.string()),
  searchQMax: v.optional(v.string()),
  searchPaMin: v.optional(v.string()),
  searchPaMax: v.optional(v.string()),
  searchMagMin: v.optional(v.string()),
  searchMagMax: v.optional(v.string()),
  searchMeanMueMin: v.optional(v.string()),
  searchMeanMueMax: v.optional(v.string()),
  searchNucleus: v.optional(v.boolean()),
  searchTotalClassificationsMin: v.optional(v.string()),
  searchTotalClassificationsMax: v.optional(v.string()),
  searchNumVisibleNucleusMin: v.optional(v.string()),
  searchNumVisibleNucleusMax: v.optional(v.string()),
  searchNumAwesomeFlagMin: v.optional(v.string()),
  searchNumAwesomeFlagMax: v.optional(v.string()),
  searchNumFailedFittingMin: v.optional(v.string()),
  searchNumFailedFittingMax: v.optional(v.string()),
  searchTotalAssignedMin: v.optional(v.string()),
  searchTotalAssignedMax: v.optional(v.string()),
  searchAwesome: v.optional(v.boolean()),
  searchValidRedshift: v.optional(v.boolean()),
  searchVisibleNucleus: v.optional(v.boolean()),
};
